### PR TITLE
New directory layout

### PR DESCRIPTION
**Pull request by futurejones**
Updated directory structure as discussed here - https://github.com/apple/swift-installer-scripts/pull/33#issuecomment-939198955

```bash
swift-installer-scripts
  └ platforms
        ├ Linux
        │   ├ README
        │   ├ Docs - contains master design docs, road map etc.
        │   ├ DEB
        │   │   ├ README
        │   │   ├ Docs - contains information specific to .deb packages
        │   │   ├ Debian - contains information specific to the distribution
        │   │   │   ├ buster - contains information specific to the version
        │   │   │   ├ bullseye
        │   │   │   └ ...
        │   │   ├ Ubuntu
        │   │   │   ├ bionic
        │   │   │   ├ focal
        │   │   │   ├ hirsute
        │   │   │   └ ...
        │   │   └ ...
        │   │
        │   ├ RPM
        │   │   ├ README
        │   │   ├ Docs - contains information specific to .rpm packages
        │   │   ├ Amazonlinux
        │   │   │   ├ 2
        │   │   │   └ ...
        │   │   ├ Centos
        │   │   │   ├ 7
        │   │   │   ├ 8
        │   │   │   └ ...
        │   │   ├ Fedora
        │   │   │   ├ 33
        │   │   │   ├ 34
        │   │   │   ├ rawhide
        │   │   │   └ ...
        │   │   └ ...
        │   └ ...
        └ Windows
            └ ...
```

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
File shuffling seems to match.  As per the previous discussion - RPM and DEBs are pretty far apart in terms of what they expect and this makes that more reasonable to handle.

**Review by shahmishal — APPROVED** [review]
This will make it much easier to manage RPM and DEB packages. 

LGTM! Thanks @futurejones

**Comment by shahmishal** [comment]
@futurejones Can you update the README to include the new dir structure?

**Comment by futurejones** [comment]
@shahmishal, I have added https://github.com/apple/swift-installer-scripts/pull/55 to update readme.

**Pull request merged**
