### PR TITLE
update fedora setup to follow conventions of other RPM builders

### PR DESCRIPTION
**Pull request by tomerd**
motivation: consistentcy across RPM builders

changes:
* add docker-compose setup
* update rpmspec to use share metadata
* update Dockerfile to use updated rpmspec
* update build script to use updated Dockerfile and rpmspec
* add readme

### CODE REVIEW

**Comment by tomerd** [comment]
@shahmishal @drexin

**Comment by shahmishal** [comment]
@tomerd Can you resolve the merge conflict?

cc: @tachoknight for review

**Comment by tomerd** [comment]
needs https://github.com/apple/swift-installer-scripts/pull/85 first (formatting changes)

**Review by shahmishal — APPROVED** [review]

**Comment by tomerd** [comment]
@tachoknight thoughts? if no further feedback, we'll move forward and get this merged, and can address any future feedback in follow up PRS

**Comment by shahmishal** [comment]
@tomerd feel free to merge it

**Pull request merged**
