### PR TITLE
Add merge modules for the runtime.

### PR DESCRIPTION
**Pull request by barnson**
- For sharing, the runtime files are built into a .wixlib, which is then referenced by the merge module project to build a merge module, and then by a package project to build the runtime MSI package.
- The SDK project has references to the merge module project for each architecture, so it builds the merge modules and consumes them.
- Sample added showing how to consume the merge module for an app.

Other simplifications:
- Drop the no-longer-needed `var.` in `$(preprocessor)` references.
- Clean up XML namespaces.
- Remove no-longer-needed config.wxi.

### CODE REVIEW

**Comment by compnerd** [comment]
Testing at: https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/712/

**Review by tristanlabelle — APPROVED** [review]
Very exciting!

**Comment by compnerd** [comment]
Re-running at https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/717/

**Comment by compnerd** [comment]
The build fails with:
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj" (default target) (1:7) ->
(CoreCompile target) -> 
  C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wxs(457): error WIX0103: Cannot find the File file '!(bindpath.rtmsm.x86)\runtime.x86.msm'. The following paths were checked: !(bindpath.rtmsm.x86)\runtime.x86.msm, T:\package\sdk\runtime.x86.msm [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj]
  C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wxs(460): error WIX0103: Cannot find the File file '!(bindpath.rtmsm.amd64)\runtime.amd64.msm'. The following paths were checked: !(bindpath.rtmsm.amd64)\runtime.amd64.msm, T:\package\sdk\runtime.amd64.msm [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj]
```

**Review by compnerd — APPROVED** [review]
I do wish that we had split up the changes for the `var.` prefix removal, that would have been easy to get in early.  Just need to wait for CI now on the scripting change, but LGTM.

**Comment by barnson** [comment]
I should at least have made it a separate commit...

**Pull request merged**
