### PR TITLE
Add PackageModelSyntax.dll

### PR DESCRIPTION
**Pull request by hjyamauchi**
This reflects https://github.com/apple/swift-package-manager/pull/7467

### CODE REVIEW

**Comment by hjyamauchi** [comment]
CC @compnerd

**Comment by hjyamauchi** [comment]
CC @DougGregor This should fix the issue with spm failing to run installed from the windows installer

**Comment by hjyamauchi** [comment]
Oops the diff isn't correct. Fixing

**Comment by hjyamauchi** [comment]
Fixed. Ready for review

**Review by compnerd — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]
Thank you! Looks great

**Comment by compnerd** [comment]
@DougGregor I assume that this doesn't need to be pulled into release/6.0? Or should we get this cherry-picked?

**Comment by DougGregor** [comment]
We do need this on 6.0; I've opened a cherry-pick at https://github.com/apple/swift-installer-scripts/pull/285

**Pull request merged**
