### PR TITLE
add dependencies on zip and unzip where needed

### PR DESCRIPTION
**Pull request by tomerd**

### CODE REVIEW

**Review by shahmishal — APPROVED** [review]

**Review by compnerd — APPROVED** [review]
Seems reasonable, but please change the title - it doesn't add it everywhere, it adds it on Linux platforms.  Where is the packaging change for Windows? ;-)

**Comment by stevapple** [comment]
For Windows it seems more reasonable to add them as WinGet dependencies? If this is planned for Swift 5.9, we should remember to do that when it’s released.

**Comment by tomerd** [comment]
I think on windows we use tar?

**Comment by stevapple** [comment]
I think that’s a workaround introduced by @compnerd? `tar.exe` is basically the same program on Linux. It doesn’t support `.zip` archives. We were using it because there’s no `zip` and `unzip` installed on Swift CI. This may be something to add first.

**Comment by compnerd** [comment]
@stevapple - correct, we use `tar`, but it does support zip! (At least it did as of ~2 days ago when I tried?). The point was that this is Linux specific, not "everywhere".

**Comment by stevapple** [comment]
I tried, and that’s surprising @compnerd — yet another undocumented Microsoft magic…

You’re right that we should limit the scope to "on Linux":)

**Comment by compnerd** [comment]
@stevapple its actually less surprising and more obvious in hindsight.  The most likely source for this is BSD zip, which IIRC supports libarchive as a backend, which supports zip.

**Pull request merged**
